# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'ADBMobileSamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DrawerMenu'
  pod 'SideMenu'
  # Pods for ADBMobileSamples

end
